// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	trebuchetv1 "github.com/atlassian/voyager/pkg/apis/trebuchet/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReleaseGroups implements ReleaseGroupInterface
type FakeReleaseGroups struct {
	Fake *FakeTrebuchetV1
}

var releasegroupsResource = schema.GroupVersionResource{Group: "trebuchet", Version: "v1", Resource: "releasegroups"}

var releasegroupsKind = schema.GroupVersionKind{Group: "trebuchet", Version: "v1", Kind: "ReleaseGroup"}

// Get takes name of the releaseGroup, and returns the corresponding releaseGroup object, and an error if there is any.
func (c *FakeReleaseGroups) Get(name string, options v1.GetOptions) (result *trebuchetv1.ReleaseGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(releasegroupsResource, name), &trebuchetv1.ReleaseGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.ReleaseGroup), err
}

// List takes label and field selectors, and returns the list of ReleaseGroups that match those selectors.
func (c *FakeReleaseGroups) List(opts v1.ListOptions) (result *trebuchetv1.ReleaseGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(releasegroupsResource, releasegroupsKind, opts), &trebuchetv1.ReleaseGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &trebuchetv1.ReleaseGroupList{ListMeta: obj.(*trebuchetv1.ReleaseGroupList).ListMeta}
	for _, item := range obj.(*trebuchetv1.ReleaseGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested releaseGroups.
func (c *FakeReleaseGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(releasegroupsResource, opts))
}

// Create takes the representation of a releaseGroup and creates it.  Returns the server's representation of the releaseGroup, and an error, if there is any.
func (c *FakeReleaseGroups) Create(releaseGroup *trebuchetv1.ReleaseGroup) (result *trebuchetv1.ReleaseGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(releasegroupsResource, releaseGroup), &trebuchetv1.ReleaseGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.ReleaseGroup), err
}

// Update takes the representation of a releaseGroup and updates it. Returns the server's representation of the releaseGroup, and an error, if there is any.
func (c *FakeReleaseGroups) Update(releaseGroup *trebuchetv1.ReleaseGroup) (result *trebuchetv1.ReleaseGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(releasegroupsResource, releaseGroup), &trebuchetv1.ReleaseGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.ReleaseGroup), err
}

// Delete takes name of the releaseGroup and deletes it. Returns an error if one occurs.
func (c *FakeReleaseGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(releasegroupsResource, name), &trebuchetv1.ReleaseGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReleaseGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(releasegroupsResource, listOptions)

	_, err := c.Fake.Invokes(action, &trebuchetv1.ReleaseGroupList{})
	return err
}

// Patch applies the patch and returns the patched releaseGroup.
func (c *FakeReleaseGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *trebuchetv1.ReleaseGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(releasegroupsResource, name, pt, data, subresources...), &trebuchetv1.ReleaseGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.ReleaseGroup), err
}
