// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/atlassian/voyager/pkg/trebuchet/client/typed/trebuchet/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTrebuchetV1 struct {
	*testing.Fake
}

func (c *FakeTrebuchetV1) Releases() v1.ReleaseInterface {
	return &FakeReleases{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTrebuchetV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
