// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	trebuchetv1 "github.com/atlassian/voyager/pkg/apis/trebuchet/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServices implements ServiceInterface
type FakeServices struct {
	Fake *FakeTrebuchetV1
}

var servicesResource = schema.GroupVersionResource{Group: "trebuchet", Version: "v1", Resource: "services"}

var servicesKind = schema.GroupVersionKind{Group: "trebuchet", Version: "v1", Kind: "Service"}

// Get takes name of the service, and returns the corresponding service object, and an error if there is any.
func (c *FakeServices) Get(name string, options v1.GetOptions) (result *trebuchetv1.Service, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(servicesResource, name), &trebuchetv1.Service{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.Service), err
}

// List takes label and field selectors, and returns the list of Services that match those selectors.
func (c *FakeServices) List(opts v1.ListOptions) (result *trebuchetv1.ServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(servicesResource, servicesKind, opts), &trebuchetv1.ServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &trebuchetv1.ServiceList{ListMeta: obj.(*trebuchetv1.ServiceList).ListMeta}
	for _, item := range obj.(*trebuchetv1.ServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested services.
func (c *FakeServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(servicesResource, opts))
}

// Create takes the representation of a service and creates it.  Returns the server's representation of the service, and an error, if there is any.
func (c *FakeServices) Create(service *trebuchetv1.Service) (result *trebuchetv1.Service, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(servicesResource, service), &trebuchetv1.Service{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.Service), err
}

// Update takes the representation of a service and updates it. Returns the server's representation of the service, and an error, if there is any.
func (c *FakeServices) Update(service *trebuchetv1.Service) (result *trebuchetv1.Service, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(servicesResource, service), &trebuchetv1.Service{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.Service), err
}

// Delete takes name of the service and deletes it. Returns an error if one occurs.
func (c *FakeServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(servicesResource, name), &trebuchetv1.Service{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(servicesResource, listOptions)

	_, err := c.Fake.Invokes(action, &trebuchetv1.ServiceList{})
	return err
}

// Patch applies the patch and returns the patched service.
func (c *FakeServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *trebuchetv1.Service, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(servicesResource, name, pt, data, subresources...), &trebuchetv1.Service{})
	if obj == nil {
		return nil, err
	}
	return obj.(*trebuchetv1.Service), err
}
