// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BatchResolutionResponseType batch resolution response type
// swagger:model BatchResolutionResponseType
type BatchResolutionResponseType struct {

	// next from
	NextFrom string `json:"nextFrom,omitempty"`

	// next to
	NextTo string `json:"nextTo,omitempty"`

	// page details
	PageDetails *PageDetails `json:"pageDetails,omitempty"`

	// results
	Results []*ResolutionResponseType `json:"results"`
}

// Validate validates this batch resolution response type
func (m *BatchResolutionResponseType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePageDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BatchResolutionResponseType) validatePageDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.PageDetails) { // not required
		return nil
	}

	if m.PageDetails != nil {
		if err := m.PageDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pageDetails")
			}
			return err
		}
	}

	return nil
}

func (m *BatchResolutionResponseType) validateResults(formats strfmt.Registry) error {

	if swag.IsZero(m.Results) { // not required
		return nil
	}

	for i := 0; i < len(m.Results); i++ {
		if swag.IsZero(m.Results[i]) { // not required
			continue
		}

		if m.Results[i] != nil {
			if err := m.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BatchResolutionResponseType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BatchResolutionResponseType) UnmarshalBinary(b []byte) error {
	var res BatchResolutionResponseType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
