// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PageDetails page details
// swagger:model PageDetails
type PageDetails struct {

	// page
	Page int32 `json:"page,omitempty"`

	// page count
	PageCount int32 `json:"pageCount,omitempty"`

	// total
	Total int32 `json:"total,omitempty"`
}

// Validate validates this page details
func (m *PageDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PageDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageDetails) UnmarshalBinary(b []byte) error {
	var res PageDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
