// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/atlassian/voyager/pkg/apis/trebuchet/v1"
	scheme "github.com/atlassian/voyager/pkg/trebuchet/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ReleaseGroupsGetter has a method to return a ReleaseGroupInterface.
// A group's client should implement this interface.
type ReleaseGroupsGetter interface {
	ReleaseGroups() ReleaseGroupInterface
}

// ReleaseGroupInterface has methods to work with ReleaseGroup resources.
type ReleaseGroupInterface interface {
	Create(*v1.ReleaseGroup) (*v1.ReleaseGroup, error)
	Update(*v1.ReleaseGroup) (*v1.ReleaseGroup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ReleaseGroup, error)
	List(opts metav1.ListOptions) (*v1.ReleaseGroupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ReleaseGroup, err error)
	ReleaseGroupExpansion
}

// releaseGroups implements ReleaseGroupInterface
type releaseGroups struct {
	client rest.Interface
}

// newReleaseGroups returns a ReleaseGroups
func newReleaseGroups(c *TrebuchetV1Client) *releaseGroups {
	return &releaseGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the releaseGroup, and returns the corresponding releaseGroup object, and an error if there is any.
func (c *releaseGroups) Get(name string, options metav1.GetOptions) (result *v1.ReleaseGroup, err error) {
	result = &v1.ReleaseGroup{}
	err = c.client.Get().
		Resource("releasegroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ReleaseGroups that match those selectors.
func (c *releaseGroups) List(opts metav1.ListOptions) (result *v1.ReleaseGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ReleaseGroupList{}
	err = c.client.Get().
		Resource("releasegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested releaseGroups.
func (c *releaseGroups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("releasegroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a releaseGroup and creates it.  Returns the server's representation of the releaseGroup, and an error, if there is any.
func (c *releaseGroups) Create(releaseGroup *v1.ReleaseGroup) (result *v1.ReleaseGroup, err error) {
	result = &v1.ReleaseGroup{}
	err = c.client.Post().
		Resource("releasegroups").
		Body(releaseGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a releaseGroup and updates it. Returns the server's representation of the releaseGroup, and an error, if there is any.
func (c *releaseGroups) Update(releaseGroup *v1.ReleaseGroup) (result *v1.ReleaseGroup, err error) {
	result = &v1.ReleaseGroup{}
	err = c.client.Put().
		Resource("releasegroups").
		Name(releaseGroup.Name).
		Body(releaseGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the releaseGroup and deletes it. Returns an error if one occurs.
func (c *releaseGroups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("releasegroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *releaseGroups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("releasegroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched releaseGroup.
func (c *releaseGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ReleaseGroup, err error) {
	result = &v1.ReleaseGroup{}
	err = c.client.Patch(pt).
		Resource("releasegroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
