// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/atlassian/voyager/pkg/formation/client/typed/formation/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFormationV1 struct {
	*testing.Fake
}

func (c *FakeFormationV1) LocationDescriptors(namespace string) v1.LocationDescriptorInterface {
	return &FakeLocationDescriptors{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFormationV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
