// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	formationv1 "github.com/atlassian/voyager/pkg/apis/formation/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocationDescriptors implements LocationDescriptorInterface
type FakeLocationDescriptors struct {
	Fake *FakeFormationV1
	ns   string
}

var locationdescriptorsResource = schema.GroupVersionResource{Group: "formation.voyager.atl-paas.net", Version: "v1", Resource: "locationdescriptors"}

var locationdescriptorsKind = schema.GroupVersionKind{Group: "formation.voyager.atl-paas.net", Version: "v1", Kind: "LocationDescriptor"}

// Get takes name of the locationDescriptor, and returns the corresponding locationDescriptor object, and an error if there is any.
func (c *FakeLocationDescriptors) Get(name string, options v1.GetOptions) (result *formationv1.LocationDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(locationdescriptorsResource, c.ns, name), &formationv1.LocationDescriptor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*formationv1.LocationDescriptor), err
}

// List takes label and field selectors, and returns the list of LocationDescriptors that match those selectors.
func (c *FakeLocationDescriptors) List(opts v1.ListOptions) (result *formationv1.LocationDescriptorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(locationdescriptorsResource, locationdescriptorsKind, c.ns, opts), &formationv1.LocationDescriptorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &formationv1.LocationDescriptorList{ListMeta: obj.(*formationv1.LocationDescriptorList).ListMeta}
	for _, item := range obj.(*formationv1.LocationDescriptorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested locationDescriptors.
func (c *FakeLocationDescriptors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(locationdescriptorsResource, c.ns, opts))

}

// Create takes the representation of a locationDescriptor and creates it.  Returns the server's representation of the locationDescriptor, and an error, if there is any.
func (c *FakeLocationDescriptors) Create(locationDescriptor *formationv1.LocationDescriptor) (result *formationv1.LocationDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(locationdescriptorsResource, c.ns, locationDescriptor), &formationv1.LocationDescriptor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*formationv1.LocationDescriptor), err
}

// Update takes the representation of a locationDescriptor and updates it. Returns the server's representation of the locationDescriptor, and an error, if there is any.
func (c *FakeLocationDescriptors) Update(locationDescriptor *formationv1.LocationDescriptor) (result *formationv1.LocationDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(locationdescriptorsResource, c.ns, locationDescriptor), &formationv1.LocationDescriptor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*formationv1.LocationDescriptor), err
}

// Delete takes name of the locationDescriptor and deletes it. Returns an error if one occurs.
func (c *FakeLocationDescriptors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(locationdescriptorsResource, c.ns, name), &formationv1.LocationDescriptor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocationDescriptors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(locationdescriptorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &formationv1.LocationDescriptorList{})
	return err
}

// Patch applies the patch and returns the patched locationDescriptor.
func (c *FakeLocationDescriptors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *formationv1.LocationDescriptor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(locationdescriptorsResource, c.ns, name, pt, data, subresources...), &formationv1.LocationDescriptor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*formationv1.LocationDescriptor), err
}
