// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/atlassian/voyager/pkg/creator/client/typed/creator/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCreatorV1 struct {
	*testing.Fake
}

func (c *FakeCreatorV1) Services() v1.ServiceInterface {
	return &FakeServices{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCreatorV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
