// +build !ignore_autogenerated

// Generated code
// run `make generate` to update

// Code generated by deepcopy-gen. DO NOT EDIT.

package knownshapes

import (
	wiringplugin "github.com/atlassian/voyager/pkg/orchestration/wiring/wiringplugin"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableEnvironmentVariables) DeepCopyInto(out *BindableEnvironmentVariables) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.BindableShapeStruct.DeepCopyInto(&out.BindableShapeStruct)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableEnvironmentVariables.
func (in *BindableEnvironmentVariables) DeepCopy() *BindableEnvironmentVariables {
	if in == nil {
		return nil
	}
	out := new(BindableEnvironmentVariables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *BindableEnvironmentVariables) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableIamAccessible) DeepCopyInto(out *BindableIamAccessible) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.BindableShapeStruct.DeepCopyInto(&out.BindableShapeStruct)
	in.IAMPolicySnippet.DeepCopyInto(&out.IAMPolicySnippet)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableIamAccessible.
func (in *BindableIamAccessible) DeepCopy() *BindableIamAccessible {
	if in == nil {
		return nil
	}
	out := new(BindableIamAccessible)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *BindableIamAccessible) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
