// +build !ignore_autogenerated

// Generated code
// run `make generate` to update

// Code generated by deepcopy-gen. DO NOT EDIT.

package knownshapes

import (
	wiringplugin "github.com/atlassian/voyager/pkg/orchestration/wiring/wiringplugin"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableEnvironmentVariables) DeepCopyInto(out *BindableEnvironmentVariables) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableEnvironmentVariables.
func (in *BindableEnvironmentVariables) DeepCopy() *BindableEnvironmentVariables {
	if in == nil {
		return nil
	}
	out := new(BindableEnvironmentVariables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *BindableEnvironmentVariables) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableEnvironmentVariablesData) DeepCopyInto(out *BindableEnvironmentVariablesData) {
	*out = *in
	in.BindableShapeStruct.DeepCopyInto(&out.BindableShapeStruct)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableEnvironmentVariablesData.
func (in *BindableEnvironmentVariablesData) DeepCopy() *BindableEnvironmentVariablesData {
	if in == nil {
		return nil
	}
	out := new(BindableEnvironmentVariablesData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableIamAccessible) DeepCopyInto(out *BindableIamAccessible) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableIamAccessible.
func (in *BindableIamAccessible) DeepCopy() *BindableIamAccessible {
	if in == nil {
		return nil
	}
	out := new(BindableIamAccessible)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *BindableIamAccessible) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindableIamAccessibleData) DeepCopyInto(out *BindableIamAccessibleData) {
	*out = *in
	in.BindableShapeStruct.DeepCopyInto(&out.BindableShapeStruct)
	in.IAMPolicySnippet.DeepCopyInto(&out.IAMPolicySnippet)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindableIamAccessibleData.
func (in *BindableIamAccessibleData) DeepCopy() *BindableIamAccessibleData {
	if in == nil {
		return nil
	}
	out := new(BindableIamAccessibleData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Labelled) DeepCopyInto(out *Labelled) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Labelled.
func (in *Labelled) DeepCopy() *Labelled {
	if in == nil {
		return nil
	}
	out := new(Labelled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *Labelled) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelledData) DeepCopyInto(out *LabelledData) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelledData.
func (in *LabelledData) DeepCopy() *LabelledData {
	if in == nil {
		return nil
	}
	out := new(LabelledData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnsSubscribable) DeepCopyInto(out *SnsSubscribable) {
	*out = *in
	out.ShapeMeta = in.ShapeMeta
	in.Data.DeepCopyInto(&out.Data)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnsSubscribable.
func (in *SnsSubscribable) DeepCopy() *SnsSubscribable {
	if in == nil {
		return nil
	}
	out := new(SnsSubscribable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new wiringplugin.Shape.
func (in *SnsSubscribable) DeepCopyShape() wiringplugin.Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnsSubscribableData) DeepCopyInto(out *SnsSubscribableData) {
	*out = *in
	in.BindableShapeStruct.DeepCopyInto(&out.BindableShapeStruct)
	in.TopicARN.DeepCopyInto(&out.TopicARN)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnsSubscribableData.
func (in *SnsSubscribableData) DeepCopy() *SnsSubscribableData {
	if in == nil {
		return nil
	}
	out := new(SnsSubscribableData)
	in.DeepCopyInto(out)
	return out
}
