// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/atlassian/voyager/pkg/apis/formation/v1"
	"github.com/atlassian/voyager/pkg/formation/client/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type FormationV1Interface interface {
	RESTClient() rest.Interface
	LocationDescriptorsGetter
}

// FormationV1Client is used to interact with features provided by the formation.voyager.atl-paas.net group.
type FormationV1Client struct {
	restClient rest.Interface
}

func (c *FormationV1Client) LocationDescriptors(namespace string) LocationDescriptorInterface {
	return newLocationDescriptors(c, namespace)
}

// NewForConfig creates a new FormationV1Client for the given config.
func NewForConfig(c *rest.Config) (*FormationV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &FormationV1Client{client}, nil
}

// NewForConfigOrDie creates a new FormationV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *FormationV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new FormationV1Client for the given RESTClient.
func New(c rest.Interface) *FormationV1Client {
	return &FormationV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FormationV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
