// +build !ignore_autogenerated

// Generated code
// run `make generate` to update

// Code generated by deepcopy-gen. DO NOT EDIT.

package wiringplugin

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredShape.
func (in *UnstructuredShape) DeepCopy() *UnstructuredShape {
	if in == nil {
		return nil
	}
	out := new(UnstructuredShape)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyShape is an autogenerated deepcopy function, copying the receiver, creating a new Shape.
func (in *UnstructuredShape) DeepCopyShape() Shape {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
