// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/atlassian/voyager/pkg/orchestration/client/typed/orchestration/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOrchestrationV1 struct {
	*testing.Fake
}

func (c *FakeOrchestrationV1) States(namespace string) v1.StateInterface {
	return &FakeStates{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOrchestrationV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
