// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	orchestrationv1 "github.com/atlassian/voyager/pkg/apis/orchestration/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStates implements StateInterface
type FakeStates struct {
	Fake *FakeOrchestrationV1
	ns   string
}

var statesResource = schema.GroupVersionResource{Group: "orchestration.voyager.atl-paas.net", Version: "v1", Resource: "states"}

var statesKind = schema.GroupVersionKind{Group: "orchestration.voyager.atl-paas.net", Version: "v1", Kind: "State"}

// Get takes name of the state, and returns the corresponding state object, and an error if there is any.
func (c *FakeStates) Get(name string, options v1.GetOptions) (result *orchestrationv1.State, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(statesResource, c.ns, name), &orchestrationv1.State{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orchestrationv1.State), err
}

// List takes label and field selectors, and returns the list of States that match those selectors.
func (c *FakeStates) List(opts v1.ListOptions) (result *orchestrationv1.StateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(statesResource, statesKind, c.ns, opts), &orchestrationv1.StateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &orchestrationv1.StateList{ListMeta: obj.(*orchestrationv1.StateList).ListMeta}
	for _, item := range obj.(*orchestrationv1.StateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested states.
func (c *FakeStates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(statesResource, c.ns, opts))

}

// Create takes the representation of a state and creates it.  Returns the server's representation of the state, and an error, if there is any.
func (c *FakeStates) Create(state *orchestrationv1.State) (result *orchestrationv1.State, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(statesResource, c.ns, state), &orchestrationv1.State{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orchestrationv1.State), err
}

// Update takes the representation of a state and updates it. Returns the server's representation of the state, and an error, if there is any.
func (c *FakeStates) Update(state *orchestrationv1.State) (result *orchestrationv1.State, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(statesResource, c.ns, state), &orchestrationv1.State{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orchestrationv1.State), err
}

// Delete takes name of the state and deletes it. Returns an error if one occurs.
func (c *FakeStates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(statesResource, c.ns, name), &orchestrationv1.State{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(statesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &orchestrationv1.StateList{})
	return err
}

// Patch applies the patch and returns the patched state.
func (c *FakeStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *orchestrationv1.State, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(statesResource, c.ns, name, pt, data, subresources...), &orchestrationv1.State{})

	if obj == nil {
		return nil, err
	}
	return obj.(*orchestrationv1.State), err
}
