// Generated code
// run `make generate` to update

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/atlassian/voyager/pkg/ops/client/typed/ops/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOpsV1 struct {
	*testing.Fake
}

func (c *FakeOpsV1) Routes(namespace string) v1.RouteInterface {
	return &FakeRoutes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOpsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
